name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: '8.4.0'
      - name: Build frontend
        run: NITRO_PRESET=firebase pnpm i -D nuxi && npm run build
      - name: Build Functions
        run: npm ci
        working-directory: functions
      # - run: ls -la
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPEEDY_VALOR_379408 }}
